global:
  resolve_timeout: 5m

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'  # Replace with your Slack webhook URL
        channel: '#alerts'  # Replace with your Slack channel name
        send_resolved: true  # Optional: Send resolved notifications when alerts clear
        title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
        text: >
          *Summary*: {{ .CommonAnnotations.summary }}
          *Description*: {{ .CommonAnnotations.description }}